### ISSUE TITLE
Vagrant/Docker Client

### ISSUE THREAD

**Issue by parker20121** [aglahe/dsra-dcos#4]
Need vagrant/docker client as discussed. Should include:

Docker 1.8
Spark 1.5.0
HDFS CLI
Mesos 0.23.0 (need to watch for mesos upgrade since 0.24 has been released)

**Comment by parker20121** [comment]
Need to add private docker registry CA certificate to client since we are using self-signing certs.

**Comment by aglahe** [comment]
The 1st cut is checked in..missing a few things, but we should have folks start using it..seeing if other bugs pop up.
